# Generated by Django 4.1.11 on 2023-09-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemodel',
            name='storeType',
            field=models.CharField(choices=[('Accom', '숙박 시설'), ('restau', '식당'), ('theater', '영화관'), ('etc', '기타')], max_length=20),
        ),
    ]
