# Generated by Django 4.1.11 on 2023-09-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storemodel',
            options={'ordering': ['slug']},
        ),
        migrations.AddField(
            model_name='storemodel',
            name='slug',
            field=models.SlugField(default='slug-test', unique=True),
            preserve_default=False,
        ),
    ]
