# Generated by Django 4.1.10 on 2023-10-06 17:35

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetModel',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'targets',
                'ordering': ['slug'],
            },
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='storeType',
            field=models.CharField(choices=[('accommodation', '숙박 시설'), ('food', '식당'), ('culture', '문화시설'), ('etc', '기타')], max_length=20),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='target',
            field=models.CharField(choices=[('ALL', '장병 및 군무원'), ('ADS', '현역 용사 만'), ('OS', '장병 만'), ('PS', '직업군인 만'), ('MC', '군무원 만')], max_length=3),
        ),
    ]
