# Generated by Django 4.1.11 on 2023-09-13 13:12

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('tkey', models.TextField(default='', null=True)),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
